---
version: '3.8'

services:
  localstack-compere:
    build:
      context: .
      args:
        LOCALSTACK_VERSION: ${LOCALSTACK_VERSION:-2.2}
    volumes:
      - "./temp-persisted-data:/persisted-data"
    environment:
      - DEBUG=1
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud

  test:
    build:
      context: ./test
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      localstack-compere:
        condition: service_healthy
