name: Docker push
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to set as the published image tag, or "latest"
        type: string
        default: latest
      localstack-version:
        description: Version of localstack to use as base image tag
        type: string
        default: latest

jobs:
  buid-and-push:
    runs-on: ubuntu-latest
    env:
      LOCALSTACK_VERSION: ${{ inputs.localstack-version || 'latest' }}
      LOCALSTACK_PERSIST_VERSION: ${{ inputs.version || 'latest' }}
    steps:
      - name: Validate major.minor versions match
        run: |
          if [[ ! ($LOCALSTACK_PERSIST_VERSION =~ ^([0-9]+\.[0-9]+) && $LOCALSTACK_VERSION == ${BASH_REMATCH[1]}*) ]]
          then
            echo "major.minor versions of $LOCALSTACK_VERSION and $LOCALSTACK_PERSIST_VERSION do not match!"
            exit 1
          fi
        if: ${{ env.LOCALSTACK_PERSIST_VERSION != 'latest' }}
      - uses: actions/checkout@v3
      - run: bash test.sh
      - run: docker compose logs
        if: ${{ failure() }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: gresau/localstack-persist:${{ env.LOCALSTACK_PERSIST_VERSION }}
          build-args: LOCALSTACK_VERSION=${{ env.LOCALSTACK_VERSION }}
