name: Test
run-name: |
  Run tests for ${{
    (github.event_name == 'push' && format('commit - {0}', github.event.head_commit.message)) ||
    (github.event_name == 'pull_request' && format('PR #{0} - {1}', github.event.number, github.event.pull_request.title)) ||
    format('{0} (manually triggered)', github.ref_name)
  }}
permissions:
  contents: read

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        PROVIDER_OVERRIDE_S3: ["", "v3"]
    env:
      PROVIDER_OVERRIDE_S3: ${{ matrix.PROVIDER_OVERRIDE_S3 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: bash test.sh
      - run: docker compose logs
        if: ${{ failure() }}
